// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_cBnrc0Vsi-F6sU4qWAWaq-X5C31LrgI',
    appId: '1:507376083559:web:971dec3c2e0b6b0051aac2',
    messagingSenderId: '507376083559',
    projectId: 'taskmanager-dd7e9',
    authDomain: 'taskmanager-dd7e9.firebaseapp.com',
    storageBucket: 'taskmanager-dd7e9.appspot.com',
    measurementId: 'G-VRYSG2495Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2cB_E4on59gmQrCKasVbFKLUwncLh6fs',
    appId: '1:507376083559:android:e03f3bf7666f680651aac2',
    messagingSenderId: '507376083559',
    projectId: 'taskmanager-dd7e9',
    storageBucket: 'taskmanager-dd7e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIosR2sobCx1zR86DoeQLt138bVXt9nwY',
    appId: '1:507376083559:ios:d94424539639e57e51aac2',
    messagingSenderId: '507376083559',
    projectId: 'taskmanager-dd7e9',
    storageBucket: 'taskmanager-dd7e9.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIosR2sobCx1zR86DoeQLt138bVXt9nwY',
    appId: '1:507376083559:ios:d94424539639e57e51aac2',
    messagingSenderId: '507376083559',
    projectId: 'taskmanager-dd7e9',
    storageBucket: 'taskmanager-dd7e9.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );
}
